# Generated by Django 4.2.1 on 2023-05-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
            ],
        ),
    ]
