# Generated by Django 4.2.1 on 2023-05-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friendlist_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='user.user'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='user.user'),
        ),
    ]
